### ISSUE TITLE
readme.md typo

### ISSUE THREAD

**Issue by LanceJernigan** [beardedtim/cms#13]
Your `readme.me` has a typo in the Developing section.  On step three, the third step reads `cp .env.example` but it should be `cp .env.example .env`.

This could lead to potential confusion if a user tries to run the code but doesn't know `cp` requires the target file as the second parameter.

**Comment by beardedtim** [comment]
Good catch! Can you make a PR with that change and anything else you see wrong with the `readme`?

**Comment by beardedtim** [comment]
Closed with #15
